import React,{useState} from "react";
import {SafeAreaView,View,Text,TouchableOpacity,ScrollView,StyleSheet,Image,TextInput,Switch} from "react-native";

const C="#2cebdc",P="#7046ff",BG="#03101f",CARD="#07182f",M="#91a8c6";
const IMG={
 hero:{uri:"https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=900&q=85"},
 coach:{uri:"https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=900&q=85"},
 workout:{uri:"https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=900&q=85"}
};
const exercises=[["Bench Press","4 sets • 12 reps"],["Incline Dumbbell Press","4 sets • 12 reps"],["Shoulder Press","4 sets • 10 reps"],["Tricep Pushdown","4 sets • 15 reps"],["Dips","3 sets • 12 reps"]];
const plans=[["Muscle Gain Pro","12 Weeks"],["Weight Loss","8 Weeks"],["Full Body Fitness","10 Weeks"]];
const meals=[["Breakfast","Oatmeal with fruits","320 kcal"],["Lunch","Grilled Chicken Bowl","420 kcal"],["Dinner","Salmon with Vegetables","520 kcal"],["Snack","Protein Shake","190 kcal"]];
const trainers=[["Alex Carter","Strength Coach","4.9"],["Sophia Lee","Yoga & Flexibility","4.8"],["Ryan Miller","HIIT Specialist","4.7"]];
const posts=[["Sarah Khan","Completed Day 15 of my transformation journey! 💪","124"],["Ahmed Raza","Leg day never gets easier, but it’s always worth it! 🔥","86"],["Emma Wilson","Just hit a new PR on bench press! 🎉","210"]];

const Btn=({children,onPress,ghost=false})=><TouchableOpacity onPress={onPress} style={[s.btn,ghost&&s.ghost]}><Text style={[s.btnT,ghost&&{color:"white"}]}>{children}</Text></TouchableOpacity>;
const Card=({children})=><View style={s.card}>{children}</View>;
const H=({title,sub})=><View><Text style={s.h1}>{title}</Text>{sub&&<Text style={s.muted}>{sub}</Text>}</View>;

function Splash({go}){return <View style={s.full}><Image source={IMG.hero} style={s.bg}/><View style={s.overlay}/><View style={s.bottom}><Text style={s.logo}>AI <Text style={s.cyan}>GYM</Text></Text><Text style={s.sub}>Smarter Workouts{"\n"}Healthier You</Text><Btn onPress={()=>go("Onboarding")}>Continue →</Btn></View></View>}
function Onboarding({go}){return <View style={s.full}><Image source={IMG.coach} style={s.bg}/><View style={s.overlay}/><View style={s.bottom}><Text style={s.h1}>Personalized{"\n"}AI Fitness Coach</Text><Text style={s.sub}>Get custom workout plans, track progress and achieve your goals with AI.</Text><Btn onPress={()=>go("SignUp")}>Next →</Btn></View></View>}
function Auth({go,login=false}){return <ScrollView contentContainerStyle={s.pad}><H title={login?"Welcome Back":"Create Your Account"} sub={login?"Login to continue your fitness journey.":"Join AI GYM and start your fitness journey today."}/>{!login&&<TextInput style={s.input} placeholder="Full Name" placeholderTextColor={M}/>}<TextInput style={s.input} placeholder="Email Address" placeholderTextColor={M}/><TextInput style={s.input} placeholder="Password" placeholderTextColor={M} secureTextEntry/>{login&&<View style={s.between}><Text style={s.muted}>Remember me</Text><Text style={s.cyan}>Forgot Password?</Text></View>}<Btn onPress={()=>go("Home")}>{login?"Login":"Create Account"}</Btn><Text style={s.center}>Or continue with</Text><View style={s.row}><Btn ghost>Google</Btn><Btn ghost>Apple</Btn></View><TouchableOpacity onPress={()=>go(login?"SignUp":"Login")}><Text style={[s.center,s.cyan]}>{login?"Don't have an account? Sign Up":"Already have an account? Login"}</Text></TouchableOpacity></ScrollView>}
function Home({go}){return <ScrollView contentContainerStyle={s.pad}><Text style={s.muted}>Good Morning</Text><Text style={s.h1}>Edward James 👋</Text><View style={s.grid2}><Card><Text style={s.muted}>Calories Burned</Text><Text style={s.big}>234</Text></Card><Card><Text style={s.muted}>Weight</Text><Text style={s.big2}>72.5 kg</Text></Card><Card><Text style={s.muted}>Workouts</Text><Text style={s.big}>7</Text></Card><Card><Text style={s.muted}>Active Plans</Text><Text style={s.big}>4</Text></Card></View><Text style={s.h2}>Quick Actions</Text><View style={s.grid2}>{[["Workout Plan","Workout"],["AI Coach","Coach"],["Nutrition","Nutrition"],["Progress","Progress"]].map(([n,k])=><TouchableOpacity key={n} style={s.quick} onPress={()=>go(k)}><Text style={s.cyan}>◈</Text><Text style={s.body}>{n}</Text></TouchableOpacity>)}</View><Card><Text style={s.muted}>Today's Workout</Text><Text style={s.h2}>Push Day</Text><Text style={s.muted}>Chest • Shoulders • Triceps</Text><Btn onPress={()=>go("Workout")}>Start Now →</Btn></Card></ScrollView>}
function Workout({go}){return <ScrollView contentContainerStyle={s.pad}><H title="Push Day" sub="Chest • Shoulders • Triceps"/><Image source={IMG.workout} style={s.photo}/>{exercises.map(([a,b])=><TouchableOpacity key={a} onPress={()=>go("Exercise")}><Card><Text style={s.h3}>{a}</Text><Text style={s.cyan}>{b}</Text></Card></TouchableOpacity>)}</ScrollView>}
function Exercise(){return <ScrollView contentContainerStyle={s.pad}><Image source={IMG.workout} style={s.photo}/><H title="Bench Press" sub="Chest • Strength • Compound"/><View style={s.grid3}><Card><Text style={s.h2}>4</Text><Text style={s.muted}>Sets</Text></Card><Card><Text style={s.h2}>12</Text><Text style={s.muted}>Reps</Text></Card><Card><Text style={s.h2}>60s</Text><Text style={s.muted}>Rest</Text></Card></View><Text style={s.h2}>How to do it?</Text>{["Lie on a flat bench with your feet firmly on the ground.","Grip the bar slightly wider than shoulder width.","Lower the bar to your chest.","Push the bar back up."].map((x,i)=><Text key={x} style={s.body}>{i+1}. {x}</Text>)}<Btn>Start Exercise</Btn></ScrollView>}
function Coach(){return <ScrollView contentContainerStyle={s.pad}><H title="AI Coach" sub="● Online"/><Card><Text style={s.body}>Hi Edward 👋{"\n"}How can I help you today?</Text></Card>{["Create a workout plan","Suggest a meal plan","Analyze my progress","Answer fitness questions"].map(x=><TouchableOpacity style={s.option} key={x}><Text style={s.body}>{x}</Text></TouchableOpacity>)}<Card><Text style={s.muted}>Your Plan</Text><Text style={s.h2}>Muscle Gain Pro</Text><Text style={s.muted}>12 Weeks Program</Text><Text style={s.cyan}>Current Goal: Build Muscle</Text></Card><TextInput style={s.input} placeholder="Type your message..." placeholderTextColor={M}/></ScrollView>}
function Nutrition(){return <ScrollView contentContainerStyle={s.pad}><H title="Nutrition" sub="Today • Weekly • Insights"/><Card><Text style={s.big}>1,450</Text><Text style={s.muted}>of 2,300 kcal</Text></Card>{[["Protein","120g / 170g"],["Carbs","100g / 250g"],["Fats","60g / 70g"]].map(([a,b])=><Card key={a}><Text style={s.body}>{a}</Text><Text style={s.cyan}>{b}</Text></Card>)}<Text style={s.h2}>Meals</Text>{meals.map(x=><Card key={x[0]}><Text style={s.h3}>{x[0]}</Text><Text style={s.muted}>{x[1]}</Text><Text style={s.cyan}>{x[2]}</Text></Card>)}</ScrollView>}
function Progress(){return <ScrollView contentContainerStyle={s.pad}><H title="Progress" sub="Weight • Body • Strength"/><Card><Text style={s.big}>72.5 kg</Text><Text style={s.cyan}>+ 2.5 kg</Text></Card><View style={s.grid3}><Card><Text style={s.h2}>22.1</Text><Text style={s.muted}>BMI</Text></Card><Card><Text style={s.h2}>14.5%</Text><Text style={s.muted}>Body Fat</Text></Card><Card><Text style={s.h2}>54.2 kg</Text><Text style={s.muted}>Muscle Mass</Text></Card></View><Btn>Set New Goal</Btn></ScrollView>}
function Plans(){return <ScrollView contentContainerStyle={s.pad}><H title="Plans"/>{plans.map(x=><Card key={x[0]}><Text style={s.h2}>{x[0]}</Text><Text style={s.muted}>{x[1]}</Text><Btn ghost>View Plan</Btn></Card>)}</ScrollView>}
function Challenges(){return <ScrollView contentContainerStyle={s.pad}><H title="Challenges"/>{[["30 Day Fitness Challenge","65%"],["10K Steps Daily","30%"],["Plank Challenge","20%"]].map(x=><Card key={x[0]}><Text style={s.h2}>{x[0]}</Text><Text style={s.cyan}>{x[1]} complete</Text></Card>)}</ScrollView>}
function Community(){return <ScrollView contentContainerStyle={s.pad}><H title="Community" sub="Feed • Groups • Leaders"/>{posts.map(x=><Card key={x[0]}><Text style={s.h3}>{x[0]}</Text><Text style={s.body}>{x[1]}</Text><Text style={s.muted}>♥ {x[2]}</Text></Card>)}</ScrollView>}
function Trainers(){return <ScrollView contentContainerStyle={s.pad}><H title="Trainers"/>{trainers.map(x=><Card key={x[0]}><Text style={s.h2}>{x[0]}</Text><Text style={s.cyan}>{x[1]}</Text><Text style={s.muted}>★ {x[2]}</Text></Card>)}</ScrollView>}
function Notifications(){return <ScrollView contentContainerStyle={s.pad}><H title="Notifications"/>{["Workout Reminder — Time for your Push Day workout","New Achievement — You completed 10 workouts!","Challenge Update — You're 65% through the 30 Day Fitness Challenge","Weekly Report — Your progress report is ready"].map(x=><Card key={x}><Text style={s.body}>{x}</Text></Card>)}</ScrollView>}
function Achievements(){return <ScrollView contentContainerStyle={s.pad}><H title="Achievements"/><Card><Text style={{fontSize:60}}>🏅</Text><Text style={s.h2}>10 Workouts Completed</Text></Card><Card><Text style={s.h2}>Next Achievement</Text><Text style={s.muted}>Complete 20 Workouts</Text><Text style={s.cyan}>10 / 20</Text></Card></ScrollView>}
function Profile({go}){return <ScrollView contentContainerStyle={s.pad}><H title="Profile"/><Card><Text style={s.h2}>Edward James</Text><Text style={s.cyan}>Premium Member</Text><Text style={s.body}>48 Workouts • 12 Plans • 72.5 kg</Text></Card>{[["My Plan","Plans"],["Achievements","Achievements"],["Settings","Settings"],["Help & Support","Home"]].map(([a,b])=><TouchableOpacity key={a} onPress={()=>go(b)}><Card><Text style={s.body}>{a} ›</Text></Card></TouchableOpacity>)}<Card><Text style={s.cyan}>Premium Plan</Text><Text style={s.h2}>$9.99 / month</Text><Text style={s.muted}>Next billing: 12 Jun 2026</Text></Card></ScrollView>}
function Settings(){const [on,setOn]=useState(true);return <ScrollView contentContainerStyle={s.pad}><H title="Settings"/>{["Account","Privacy","Appearance","Units","Language","Connected Apps"].map(x=><Card key={x}><Text style={s.h3}>{x}</Text></Card>)}<Card><View style={s.between}><Text style={s.h3}>Notifications</Text><Switch value={on} onValueChange={setOn} trackColor={{true:C}}/></View></Card></ScrollView>}
function Premium(){return <ScrollView contentContainerStyle={s.pad}><H title="Premium Plan"/><Card><Text style={s.h2}>$9.99 / month</Text><Text style={s.body}>✓ AI workout plans{"\n"}✓ Nutrition guidance{"\n"}✓ Advanced progress{"\n"}✓ Exclusive challenges</Text><Btn>Upgrade Now</Btn></Card></ScrollView>}

const map={Splash,Onboarding,SignUp:p=><Auth {...p}/>,Login:p=><Auth {...p} login/>,Home,Workout,Exercise,Coach,Nutrition,Progress,Plans,Challenges,Community,Trainers,Notifications,Achievements,Profile,Settings,Premium};
const tabs=[["Home","Home"],["Workout","Workout"],["Nutrition","Nutrition"],["Community","Community"],["Profile","Profile"]];
export default function App(){const [screen,setScreen]=useState("Splash");const Cmp=map[screen]||Home;const show=["Home","Workout","Exercise","Coach","Nutrition","Progress","Plans","Challenges","Community","Trainers","Notifications","Achievements","Profile","Settings","Premium"].includes(screen);return <SafeAreaView style={s.root}><View style={{flex:1}}><Cmp go={setScreen}/></View>{show&&<View style={s.nav}>{tabs.map(([n,k])=><TouchableOpacity key={n} onPress={()=>setScreen(k)}><Text style={{color:screen===k?C:M,fontSize:11}}>{n}</Text></TouchableOpacity>)}</View>}</SafeAreaView>}

const s=StyleSheet.create({root:{flex:1,backgroundColor:BG},full:{flex:1,backgroundColor:BG},bg:{...StyleSheet.absoluteFillObject,width:"100%",height:"100%",resizeMode:"cover"},overlay:{...StyleSheet.absoluteFillObject,backgroundColor:"rgba(3,10,24,.48)"},bottom:{position:"absolute",left:22,right:22,bottom:34,gap:14},logo:{fontSize:44,color:"white",fontWeight:"900"},h1:{fontSize:31,color:"white",fontWeight:"900"},h2:{fontSize:21,color:"white",fontWeight:"850"},h3:{fontSize:16,color:"white",fontWeight:"800"},big:{fontSize:44,color:"white",fontWeight:"950"},big2:{fontSize:27,color:"white",fontWeight:"900"},body:{fontSize:14,color:"white",lineHeight:21},sub:{fontSize:16,color:"#d5e3f2",lineHeight:23},muted:{color:M},cyan:{color:C,fontWeight:"800"},center:{textAlign:"center",color:M,marginTop:8},pad:{padding:19,paddingBottom:100,gap:11},card:{backgroundColor:CARD,borderColor:"#173a60",borderWidth:1,borderRadius:18,padding:16,marginVertical:3},btn:{backgroundColor:C,borderRadius:13,padding:14,alignItems:"center",marginTop:8,minWidth:110},ghost:{backgroundColor:"#0b1d38",borderColor:"#21466f",borderWidth:1},btnT:{color:"#04131a",fontWeight:"900"},input:{backgroundColor:CARD,borderColor:"#1c456f",borderWidth:1,borderRadius:12,padding:13,color:"white",marginVertical:4},row:{flexDirection:"row",gap:9,flexWrap:"wrap"},between:{flexDirection:"row",justifyContent:"space-between",alignItems:"center"},grid2:{flexDirection:"row",flexWrap:"wrap",gap:9},grid3:{flexDirection:"row",gap:7},quick:{width:"48%",backgroundColor:CARD,borderColor:"#18466e",borderWidth:1,borderRadius:15,padding:14,gap:5},option:{backgroundColor:"#0d2343",borderColor:"#224a75",borderWidth:1,borderRadius:13,padding:14,marginVertical:3},photo:{width:"100%",height:220,borderRadius:18,resizeMode:"cover"},nav:{flexDirection:"row",justifyContent:"space-around",paddingVertical:13,backgroundColor:"#06152b",borderTopWidth:1,borderTopColor:"#18395a"}});