import React,{useState} from "react";
import {SafeAreaView,View,Text,TouchableOpacity,ScrollView,StyleSheet,Image,TextInput,Switch} from "react-native";
const A={uri:"https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=1200&q=85"};
const B={uri:"https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1200&q=85"};
const W={uri:"https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=1200&q=85"};
const T={uri:"https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=1200&q=85"};
const P={uri:"https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=1200&q=85"};
const C="#24f3df",BG="#050b18",CARD="#0a1830",M="#93a8c4";
const Btn=({children,onPress})=><TouchableOpacity onPress={onPress} style={s.btn}><Text style={s.btnT}>{children}</Text></TouchableOpacity>;
const Card=({children})=><View style={s.card}>{children}</View>;
const H=({title,sub})=><><Text style={s.h1}>{title}</Text>{sub&&<Text style={s.muted}>{sub}</Text>}</>;
function Splash({go}){return <View style={s.full}><Image source={A} style={s.bgimg}/><View style={s.overlay}/><View style={s.bottom}><Text style={s.logo}>AI <Text style={s.cyan}>GYM</Text></Text><Text style={s.sub}>Smarter Workouts{"
"}Healthier You</Text><Btn onPress={()=>go("Onboarding")}>→</Btn></View></View>}
function Onboarding({go}){return <View style={s.full}><Image source={B} style={s.bgimg}/><View style={s.overlay}/><View style={s.bottom}><Text style={s.h1}>Personalized{"
"}AI Fitness Coach</Text><Text style={s.sub}>Get custom workout plans, track progress and achieve your goals with AI.</Text><Btn onPress={()=>go("SignUp")}>Next →</Btn></View></View>}
function Auth({go,login=false}){return <ScrollView contentContainerStyle={s.pad}><H title={login?"Welcome Back":"Create
Your Account"} sub={login?"Login to continue your fitness journey.":"Join AI GYM and start your fitness journey today."}/>{!login&&<TextInput style={s.input} placeholder="Full Name" placeholderTextColor={M}/>}<TextInput style={s.input} placeholder="Email Address" placeholderTextColor={M}/><TextInput style={s.input} placeholder="Password" placeholderTextColor={M}/><Btn onPress={()=>go("Home")}>{login?"Login":"Create Account"}</Btn><Text style={s.center}>Or continue with</Text><View style={s.row}><TouchableOpacity style={s.social}><Text style={s.body}>Google</Text></TouchableOpacity><TouchableOpacity style={s.social}><Text style={s.body}>Apple</Text></TouchableOpacity></View></ScrollView>}
function Home({go}){return <ScrollView contentContainerStyle={s.pad}><Text style={s.muted}>Good Morning</Text><Text style={s.h1}>Edward James 👋</Text><Card><Text style={s.muted}>Today's Progress</Text><Text style={s.big}>234</Text><Text style={s.body}>Calories Burned</Text></Card><View style={s.row}>{[["Workout Plan","Workout"],["AI Coach","Coach"],["Nutrition","Nutrition"],["Progress","Progress"]].map(([n,k])=><TouchableOpacity key={n} style={s.quick} onPress={()=>go(k)}><Text style={s.cyan}>◈</Text><Text style={s.small}>{n}</Text></TouchableOpacity>)}</View><Card><Text style={s.muted}>Today's Workout</Text><Text style={s.h2}>Push Day</Text><Text style={s.muted}>Chest • Shoulders • Triceps</Text><Btn onPress={()=>go("Workout")}>Start Now →</Btn></Card></ScrollView>}
function Workout({go}){return <ScrollView contentContainerStyle={s.pad}><H title="Push Day" sub="5 exercises · approx. 50 min"/>{[["Bench Press","4 × 12"],["Incline Dumbbell Press","4 × 12"],["Shoulder Press","4 × 10"],["Tricep Pushdown","4 × 15"],["Dips","3 × 12"]].map(([a,b])=><TouchableOpacity key={a} onPress={()=>go("Exercise")}><Card><Text style={s.h2}>{a}</Text><Text style={s.cyan}>{b}</Text></Card></TouchableOpacity>)}</ScrollView>}
function Exercise(){return <ScrollView contentContainerStyle={s.pad}><Image source={W} style={s.workout}/><H title="Bench Press" sub="Chest · Strength · Compound"/><View style={s.row}><Card><Text style={s.h2}>4</Text><Text style={s.muted}>Sets</Text></Card><Card><Text style={s.h2}>12</Text><Text style={s.muted}>Reps</Text></Card><Card><Text style={s.h2}>60s</Text><Text style={s.muted}>Rest</Text></Card></View><Text style={s.h2}>How to do it?</Text>{["Lie on a flat bench with your feet firmly on the ground.","Grip the bar slightly wider than shoulder width.","Lower the bar to your chest.","Push the bar back up."].map((x,i)=><Text key={x} style={s.body}>{i+1}. {x}</Text>)}<Btn>Start Exercise</Btn></ScrollView>}
function Coach(){return <View style={s.pad}><H title="AI Coach"/><Text style={s.cyan}>● Online</Text><Card><Text style={s.body}>Hi Edward 👋{"
"}How can I help you today?</Text></Card>{["Create a workout plan","Suggest a meal plan","Analyze my progress","Answer fitness questions"].map(x=><TouchableOpacity key={x} style={s.option}><Text style={s.body}>{x}</Text></TouchableOpacity>)}</View>}
function Nutrition(){return <ScrollView contentContainerStyle={s.pad}><H title="Nutrition"/><Card><Text style={s.big}>1,450</Text><Text style={s.muted}>of 2,300 kcal</Text></Card>{[["Protein","120g / 170g"],["Carbs","100g / 250g"],["Fats","60g / 70g"]].map(([a,b])=><Card key={a}><Text style={s.body}>{a}</Text><Text style={s.cyan}>{b}</Text></Card>)}<Text style={s.h2}>Meals</Text>{[["Breakfast","Oatmeal with fruits","320 kcal"],["Lunch","Grilled Chicken Bowl","420 kcal"],["Dinner","Salmon with Vegetables","520 kcal"],["Snack","Protein Shake","190 kcal"]].map(x=><Card key={x[0]}><Text style={s.body}>{x[0]}</Text><Text style={s.muted}>{x[1]}</Text><Text style={s.cyan}>{x[2]}</Text></Card>)}</ScrollView>}
function Progress(){return <ScrollView contentContainerStyle={s.pad}><H title="Progress"/><Card><Text style={s.big}>72.5 kg</Text><Text style={s.cyan}>+ 2.5 kg</Text></Card><View style={s.row}><Card><Text style={s.h2}>22.1</Text><Text style={s.muted}>BMI</Text></Card><Card><Text style={s.h2}>14.5%</Text><Text style={s.muted}>Body Fat</Text></Card><Card><Text style={s.h2}>54.2 kg</Text><Text style={s.muted}>Muscle</Text></Card></View><Btn>Set New Goal</Btn></ScrollView>}
function Plans(){return <ScrollView contentContainerStyle={s.pad}><H title="Plans"/>{[["Muscle Gain Pro","12 Weeks · 36 Workouts"],["Weight Loss","8 Weeks · 24 Workouts"],["Full Body Fitness","10 Weeks · 30 Workouts"]].map(x=><Card key={x[0]}><Text style={s.h2}>{x[0]}</Text><Text style={s.muted}>{x[1]}</Text><Btn>View Plan</Btn></Card>)}</ScrollView>}
function Challenges(){return <ScrollView contentContainerStyle={s.pad}><H title="Challenges"/>{[["30 Day Fitness Challenge","65%"],["10K Steps Daily","30%"],["Plank Challenge","20%"]].map(x=><Card key={x[0]}><Text style={s.h2}>{x[0]}</Text><Text style={s.cyan}>{x[1]} complete</Text></Card>)}</ScrollView>}
function Community(){return <ScrollView contentContainerStyle={s.pad}><H title="Community"/>{[["Sarah Khan","Completed Day 15 of my transformation journey! 💪","124"],["Ahmed Raza","Leg day never gets easier, but it’s always worth it! 🔥","86"],["Emma Wilson","Just hit a new PR on bench press! 🎉","210"]].map(x=><Card key={x[0]}><Text style={s.h2}>{x[0]}</Text><Text style={s.body}>{x[1]}</Text><Text style={s.muted}>♡ {x[2]}</Text></Card>)}</ScrollView>}
function Trainers(){return <ScrollView contentContainerStyle={s.pad}><Image source={T} style={s.workout}/><H title="Trainers"/>{[["Alex Carter","Strength Coach","4.9"],["Sophia Lee","Yoga & Mobility","4.8"],["Ryan Miller","HIIT Specialist","4.9"],["Emma Wilson","Nutrition Expert","4.8"]].map(x=><Card key={x[0]}><Text style={s.h2}>{x[0]}</Text><Text style={s.cyan}>{x[1]}</Text><Text style={s.muted}>★ {x[2]}</Text></Card>)}</ScrollView>}
function Notifications(){return <ScrollView contentContainerStyle={s.pad}><H title="Notifications"/>{[["Workout Reminder","Time for your Push Day workout","2 min ago"],["New Achievement","You completed 10 workouts!","1 hour ago"],["Challenge Update","You're 65% through 30 Day Challenge","3 hours ago"]].map(x=><Card key={x[0]}><Text style={s.h2}>{x[0]}</Text><Text style={s.body}>{x[1]}</Text><Text style={s.muted}>{x[2]}</Text></Card>)}</ScrollView>}
function Achievements(){return <ScrollView contentContainerStyle={s.pad}><H title="Achievements"/><Card><Text style={{fontSize:64}}>🏅</Text><Text style={s.h2}>10 Workouts Completed</Text></Card></ScrollView>}
function Profile({go}){return <ScrollView contentContainerStyle={s.pad}><Image source={P} style={s.workout}/><H title="Edward James" sub="Premium Member"/><Card><Text style={s.body}>48 Workouts · 12 Plans · 72.5 kg</Text></Card>{[["My Plan","Plans"],["Achievements","Achievements"],["Settings","Settings"]].map(([x,k])=><TouchableOpacity key={x} onPress={()=>go(k)}><Card><Text style={s.body}>{x} ›</Text></Card></TouchableOpacity>)}<TouchableOpacity onPress={()=>go("Premium")}><Card><Text style={s.cyan}>Premium Plan</Text><Text style={s.h2}>$9.99 / month</Text></Card></TouchableOpacity></ScrollView>}
function Settings(){const [on,setOn]=useState(true);return <ScrollView contentContainerStyle={s.pad}><H title="Settings"/>{["Account","Privacy","Appearance","Units","Language","Connected Apps"].map(x=><Card key={x}><Text style={s.body}>{x} ›</Text></Card>)}<Card><View style={s.space}><Text style={s.body}>Notifications</Text><Switch value={on} onValueChange={setOn}/></View></Card></ScrollView>}
function Premium({go}){return <ScrollView contentContainerStyle={s.pad}><H title="Premium Plan"/>{[["Basic","Free"],["Premium","$9.99 / month"],["Elite","$19.99 / month"]].map(x=><Card key={x[0]}><Text style={s.h2}>{x[0]}</Text><Text style={s.cyan}>{x[1]}</Text><Text style={s.body}>✓ Workout tracking{"
"}✓ AI features{"
"}✓ Progress insights</Text><Btn onPress={()=>x[0]==="Premium"&&go("Success")}>Choose {x[0]}</Btn></Card>)}</ScrollView>}
function Success({go}){return <View style={[s.pad,{justifyContent:"center",flex:1}]}><Text style={{fontSize:74,textAlign:"center"}}>✓</Text><Text style={[s.h1,{textAlign:"center"}]}>You're All Set!</Text><Text style={[s.cyan,{textAlign:"center"}]}>Welcome to Premium</Text><Btn onPress={()=>go("Home")}>Start Exploring</Btn></View>}
const screens={Splash,Onboarding,SignUp:p=><Auth {...p}/>,Login:p=><Auth {...p} login/>,Home,Workout,Exercise,Coach,Nutrition,Progress,Plans,Challenges,Community,Trainers,Notifications,Achievements,Profile,Settings,Premium,Success};
export default function App(){const [screen,setScreen]=useState("Splash");const Cmp=screens[screen];const navScreens=["Home","Workout","Nutrition","Plans","Profile"];return <SafeAreaView style={s.root}><View style={{flex:1}}><Cmp go={setScreen}/></View>{navScreens.includes(screen)&&<View style={s.nav}>{navScreens.map(k=><TouchableOpacity key={k} onPress={()=>setScreen(k)}><Text style={{color:screen===k?C:M,fontSize:11}}>{k}</Text></TouchableOpacity>)}</View>}</SafeAreaView>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:BG},full:{flex:1,backgroundColor:BG},bgimg:{...StyleSheet.absoluteFillObject,width:"100%",height:"100%",resizeMode:"cover"},overlay:{...StyleSheet.absoluteFillObject,backgroundColor:"rgba(3,8,20,.28)"},bottom:{position:"absolute",left:24,right:24,bottom:35,gap:14},logo:{fontSize:46,color:"white",fontWeight:"900"},h1:{fontSize:32,color:"white",fontWeight:"900"},h2:{fontSize:20,color:"white",fontWeight:"850"},big:{fontSize:48,color:"white",fontWeight:"950"},body:{fontSize:15,color:"white",lineHeight:22},small:{fontSize:11,color:"white"},sub:{fontSize:17,color:"#d3e3f3",lineHeight:24},muted:{color:M},cyan:{color:C,fontWeight:"800"},center:{textAlign:"center",color:M,marginTop:8},pad:{padding:20,paddingBottom:100,gap:12},card:{backgroundColor:CARD,borderColor:"#173858",borderWidth:1,borderRadius:18,padding:16,marginVertical:3},btn:{backgroundColor:C,borderRadius:14,padding:15,alignItems:"center"},btnT:{color:"#04131a",fontWeight:"900"},input:{backgroundColor:CARD,borderColor:"#1b4268",borderWidth:1,borderRadius:13,padding:14,color:"white",marginVertical:4},row:{flexDirection:"row",gap:10,flexWrap:"wrap"},quick:{width:"22%",minWidth:72,backgroundColor:CARD,borderColor:"#174469",borderWidth:1,borderRadius:15,padding:13,alignItems:"center",gap:5},social:{flex:1,backgroundColor:CARD,borderColor:"#1b4268",borderWidth:1,borderRadius:13,padding:14,alignItems:"center"},option:{backgroundColor:"#0d2343",borderColor:"#224a75",borderWidth:1,borderRadius:13,padding:14,marginVertical:4},workout:{width:"100%",height:230,borderRadius:18,resizeMode:"cover"},nav:{flexDirection:"row",justifyContent:"space-around",paddingVertical:13,backgroundColor:"#07152b",borderTopWidth:1,borderTopColor:"#18395a"},space:{flexDirection:"row",justifyContent:"space-between",alignItems:"center"}})