import React,{useEffect,useMemo,useState} from "react";
import AsyncStorage from "@react-native-async-storage/async-storage";
import {SafeAreaView,View,Text,TouchableOpacity,ScrollView,StyleSheet,Image,TextInput,Switch} from "react-native";
import {workouts,meals,plans,trainers,challenges,notifications,posts} from "./src/data";
import {theme as T} from "./src/theme";
const hero={uri:"https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=1200&q=85"};
const bench={uri:"https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=1200&q=85"};
const nutritionImg={uri:"https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&w=1200&q=85"};
const Card=({children,style})=><View style={[s.card,style]}>{children}</View>;
const Btn=({children,onPress,ghost=false})=><TouchableOpacity onPress={onPress} style={[s.btn,ghost&&s.ghost]}><Text style={[s.btnT,ghost&&{color:T.text}]}>{children}</Text></TouchableOpacity>;
const H=({title,sub})=><View style={{gap:4}}><Text style={s.h1}>{title}</Text>{sub&&<Text style={s.muted}>{sub}</Text>}</View>;
const ProgressBar=({value})=><View style={s.track}><View style={[s.fill,{width:value+"%"}]}/></View>;
const Stat=({v,l,accent})=><Card style={s.stat}><Text style={[s.statV,accent&&{color:accent}]}>{v}</Text><Text style={s.muted}>{l}</Text></Card>;

function Splash({go}){return <View style={s.full}><Image source={hero} style={s.bgimg}/><View style={s.overlay}/><View style={s.bottom}><Text style={s.logo}>AI <Text style={s.cyan}>GYM</Text></Text><Text style={s.sub}>Smarter Workouts{"\n"}Healthier You</Text><Btn onPress={()=>go("Onboarding")}>Get Started →</Btn></View></View>}
function Onboarding({go}){return <View style={s.full}><Image source={hero} style={s.bgimg}/><View style={s.overlay}/><View style={s.bottom}><Text style={s.kicker}>AI-POWERED FITNESS</Text><Text style={s.h1}>Your Personal{"\n"}AI Fitness Coach</Text><Text style={s.sub}>Custom workouts, nutrition guidance and progress insights in one premium experience.</Text><Btn onPress={()=>go("SignUp")}>Continue →</Btn><TouchableOpacity onPress={()=>go("Login")}><Text style={s.center}>I already have an account</Text></TouchableOpacity></View></View>}
function Auth({go,login}){const [name,setName]=useState("");const [email,setEmail]=useState(login?"edward@gainz.ai":"");const [password,setPassword]=useState("");const [confirm,setConfirm]=useState("");const [error,setError]=useState("");const submit=()=>{if(!email.includes("@"))return setError("Enter a valid email address.");if(password.length<6)return setError("Password must be at least 6 characters.");if(!login&&!name.trim())return setError("Full Name is required.");if(!login&&password!==confirm)return setError("Passwords do not match.");setError("");go(login?"Home":"ProfileSetup")};return <ScrollView contentContainerStyle={s.pad}><H title={login?"Welcome Back":"Create Your Account"} sub={login?"Login to continue your fitness journey.":"Join AI GYM and start your fitness journey today."}/>{!login&&<TextInput value={name} onChangeText={setName} style={s.input} placeholder="Full Name" placeholderTextColor={T.muted}/>}<TextInput value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" style={s.input} placeholder="Email Address" placeholderTextColor={T.muted}/><TextInput value={password} onChangeText={setPassword} secureTextEntry style={s.input} placeholder="Password" placeholderTextColor={T.muted}/>{!login&&<TextInput value={confirm} onChangeText={setConfirm} secureTextEntry style={s.input} placeholder="Confirm Password" placeholderTextColor={T.muted}/>} {!!error&&<Card style={{borderColor:T.danger}}><Text style={{color:T.danger}}>{error}</Text></Card>}<Btn onPress={submit}>{login?"Login":"Create Account"}</Btn><Text style={s.center}>Or continue with</Text><View style={s.row}><Btn ghost>Google</Btn><Btn ghost>Apple</Btn></View><TouchableOpacity onPress={()=>go(login?"SignUp":"Login")}><Text style={s.center}>{login?"Don’t have an account? Sign Up":"Already have an account? Login"}</Text></TouchableOpacity>{login&&<TouchableOpacity onPress={()=>go("ForgotPassword")}><Text style={s.cyan}>Forgot Password?</Text></TouchableOpacity>}</ScrollView>}

function Home({go,state,setState}){const pct=Math.round(state.calories/2300*100);return <ScrollView contentContainerStyle={s.pad}><View style={s.space}><View><Text style={s.muted}>Good Morning</Text><Text style={s.h1}>Edward James 👋</Text></View><TouchableOpacity onPress={()=>go("Notifications")} style={s.icon}><Text>●</Text></TouchableOpacity></View><Card><Text style={s.kicker}>TODAY'S PROGRESS</Text><View style={s.space}><View><Text style={s.big}>{state.calories}</Text><Text style={s.muted}>Calories Burned</Text></View><View style={s.ring}><Text style={s.ringText}>{pct}%</Text></View></View></Card><View style={s.row}>{[["▣","Workout Plan","Workouts"],["✦","AI Coach","Coach"],["◉","Nutrition","Nutrition"],["⌁","Progress","Progress"],["⌕","Search","Search"],["☾","Recovery","Recovery"]].map(([i,n,k])=><TouchableOpacity key={n} style={s.quick} onPress={()=>go(k)}><Text style={s.iconText}>{i}</Text><Text style={s.small}>{n}</Text></TouchableOpacity>)}</View><Card><Text style={s.kicker}>TODAY'S WORKOUT</Text><Text style={s.h2}>Push Day</Text><Text style={s.muted}>Chest • Shoulders • Triceps</Text><View style={s.row}><Text style={s.tag}>5 exercises</Text><Text style={s.tag}>50 min</Text></View><Btn onPress={()=>go("WorkoutDetail")}>Start Now →</Btn></Card><View style={s.grid2}><Stat v="72.5 kg" l="Weight" accent={T.cyan}/><Stat v="7" l="Workouts"/><Stat v="12 days" l="Streak" accent={T.good}/><Stat v="4" l="Active Plans"/></View><Card><View style={s.space}><Text style={s.h2}>Hydration</Text><Text style={s.cyan}>{state.water}/8 glasses</Text></View><ProgressBar value={state.water/8*100}/><Btn ghost onPress={()=>setState(v=>({...v,water:Math.min(8,v.water+1)}))}>+ Add Water</Btn></Card></ScrollView>}

function Workouts({go}){return <ScrollView contentContainerStyle={s.pad}><H title="Workouts" sub="Choose a plan or continue today’s session."/><View style={s.row}>{["All","Strength","Cardio","Mobility"].map((x,i)=><Text key={x} style={[s.tag,i===0&&s.tagActive]}>{x}</Text>)}</View>{workouts.map(w=><TouchableOpacity key={w.id} onPress={()=>go("WorkoutDetail")}><Card><View style={s.space}><View style={{flex:1}}><Text style={s.kicker}>{w.level.toUpperCase()}</Text><Text style={s.h2}>{w.name}</Text><Text style={s.muted}>{w.subtitle}</Text></View><Text style={s.cyan}>{w.duration}</Text></View></Card></TouchableOpacity>)}</ScrollView>}
function WorkoutDetail({go,state,setState}){const done=state.workoutDone;return <ScrollView contentContainerStyle={s.pad}><Image source={bench} style={s.cover}/><H title="Push Day" sub="Chest • Shoulders • Triceps"/><View style={s.grid3}><Stat v="5" l="Exercises"/><Stat v="50m" l="Duration"/><Stat v="320" l="kcal"/></View>{workouts[0].exercises.map((e,i)=><TouchableOpacity key={e[0]} onPress={()=>go("Exercise")}><Card><View style={s.space}><View><Text style={s.h3}>{e[0]}</Text><Text style={s.muted}>{e[1]} • {e[2]} rest</Text></View><Text style={done||i<state.exerciseIndex?s.check:""}>{done||i<state.exerciseIndex?"✓":"›"}</Text></View></Card></TouchableOpacity>)}<Btn onPress={()=>setState(v=>({...v,workoutDone:true,calories:v.calories+320,exerciseIndex:5}))}>{done?"Workout Completed ✓":"Complete Workout"}</Btn></ScrollView>}
function Exercise({go}){return <ScrollView contentContainerStyle={s.pad}><Image source={bench} style={s.cover}/><H title="Bench Press" sub="Chest • Strength • Compound"/><View style={s.grid3}><Stat v="4" l="Sets"/><Stat v="12" l="Reps"/><Stat v="60s" l="Rest"/></View><Card><Text style={s.h2}>How to do it</Text>{["Lie on a flat bench with your feet firmly on the ground.","Grip the bar slightly wider than shoulder width.","Lower the bar to your chest under control.","Push the bar back up without bouncing."].map((x,i)=><Text key={x} style={s.body}>{i+1}. {x}</Text>)}</Card><Btn>Start Set</Btn><Btn ghost onPress={()=>go&&go("WorkoutTimer")}>Open Rest Timer</Btn></ScrollView>}

function Coach(){const [messages,setMessages]=useState([{me:false,text:"Hi Edward 👋 How can I help you today?"}]);const [q,setQ]=useState("");const send=(text=q)=>{if(!text.trim())return;setMessages(m=>[...m,{me:true,text},{me:false,text:"Based on your Muscle Gain Pro goal, I recommend keeping progressive overload, hitting 170g protein, and protecting recovery."}]);setQ("")};return <View style={s.screen}><ScrollView contentContainerStyle={s.pad}><View style={s.space}><H title="AI Coach"/><Text style={s.cyan}>● Online</Text></View>{messages.map((m,i)=><View key={i} style={[s.bubble,m.me&&s.mine]}><Text style={s.body}>{m.text}</Text></View>)}{["Create a workout plan","Suggest a meal plan","Analyze my progress","Answer fitness questions"].map(x=><TouchableOpacity key={x} style={s.option} onPress={()=>send(x)}><Text style={s.body}>{x}</Text></TouchableOpacity>)}</ScrollView><View style={s.composer}><TextInput value={q} onChangeText={setQ} placeholder="Ask your AI coach..." placeholderTextColor={T.muted} style={[s.input,{flex:1}]}/><TouchableOpacity onPress={()=>send()} style={s.send}><Text>➤</Text></TouchableOpacity></View></View>}

function Nutrition({state,setState}){return <ScrollView contentContainerStyle={s.pad}><Image source={nutritionImg} style={s.banner}/><H title="Nutrition" sub="Today • Weekly • Insights"/><Card><View style={s.space}><View><Text style={s.big}>{state.foodCalories}</Text><Text style={s.muted}>of 2,300 kcal</Text></View><View style={s.ring}><Text style={s.ringText}>{Math.round(state.foodCalories/2300*100)}%</Text></View></View></Card>{[["Protein","120g / 170g",71],["Carbs","100g / 250g",40],["Fats","60g / 70g",86]].map(x=><Card key={x[0]}><View style={s.space}><Text style={s.h3}>{x[0]}</Text><Text style={s.muted}>{x[1]}</Text></View><ProgressBar value={x[2]}/></Card>)}<Text style={s.h2}>Today’s Meals</Text>{meals.map((m,i)=><Card key={m[0]}><View style={s.space}><View style={{flex:1}}><Text style={s.h3}>{m[0]}</Text><Text style={s.muted}>{m[1]}</Text><Text style={s.small}>{m[3]}</Text></View><Text style={s.cyan}>{m[2]}</Text></View></Card>)}<Btn ghost onPress={()=>setState(v=>({...v,foodCalories:Math.min(2300,v.foodCalories+190)}))}>+ Log Snack</Btn></ScrollView>}
function Progress(){return <ScrollView contentContainerStyle={s.pad}><H title="Progress" sub="Weight • Body • Strength"/><Card><Text style={s.big}>72.5 kg</Text><Text style={s.cyan}>+ 2.5 kg overall</Text><View style={s.chart}>{[55,62,73,67,80,88].map((h,i)=><View key={i} style={[s.bar,{height:h}]}/>)}</View></Card><View style={s.grid3}><Stat v="22.1" l="BMI" accent={T.good}/><Stat v="14.5%" l="Body Fat"/><Stat v="54.2 kg" l="Muscle"/></View><Card><Text style={s.h2}>Strength Trend</Text><View style={s.space}><Text style={s.muted}>Bench Press</Text><Text style={s.cyan}>+11%</Text></View><ProgressBar value={78}/><View style={s.space}><Text style={s.muted}>Squat</Text><Text style={s.cyan}>+8%</Text></View><ProgressBar value={70}/></Card><Btn>Set New Goal</Btn></ScrollView>}

function Plans({state,setState}){return <ScrollView contentContainerStyle={s.pad}><H title="Plans"/>{plans.map(p=><Card key={p[0]}><Text style={s.kicker}>{p[3].toUpperCase()}</Text><Text style={s.h2}>{p[0]}</Text><Text style={s.muted}>{p[1]} • {p[2]}</Text><ProgressBar value={state.activePlan===p[0]?Math.max(p[4],45):p[4]}/><Btn ghost onPress={()=>setState(v=>({...v,activePlan:p[0]}))}>{state.activePlan===p[0]?"Active Plan ✓":"Set Active Plan"}</Btn></Card>)}</ScrollView>}
function Challenges(){return <ScrollView contentContainerStyle={s.pad}><H title="Challenges"/>{challenges.map(c=><Card key={c[0]}><Text style={s.h2}>{c[0]}</Text><Text style={s.muted}>{c[1]}</Text><ProgressBar value={c[2]}/><Text style={s.cyan}>{c[2]}% complete</Text></Card>)}</ScrollView>}
function Community(){return <ScrollView contentContainerStyle={s.pad}><H title="Community" sub="Feed • Groups • Leaders"/>{posts.map(p=><Card key={p[0]}><Text style={s.h3}>{p[0]}</Text><Text style={s.muted}>{p[1]}</Text><Text style={s.body}>{p[2]}</Text><Text style={s.small}>♥ {p[3]}   💬 {p[4]}</Text></Card>)}</ScrollView>}
function Trainers({go}){return <ScrollView contentContainerStyle={s.pad}><H title="Trainers"/>{trainers.map(t=><TouchableOpacity key={t[0]} onPress={()=>go("TrainerProfile")}><Card><View style={s.space}><View><Text style={s.h2}>{t[0]}</Text><Text style={s.cyan}>{t[1]}</Text><Text style={s.muted}>★ {t[2]} • {t[3]} clients</Text></View><View style={s.avatar}><Text style={s.avatarT}>{t[0].split(" ").map(x=>x[0]).join("")}</Text></View></View></Card></TouchableOpacity>)}</ScrollView>}
function TrainerProfile(){return <ScrollView contentContainerStyle={s.pad}><Image source={hero} style={s.cover}/><H title="Alex Carter" sub="Strength Coach • ★ 4.9"/><Card><Text style={s.h2}>About</Text><Text style={s.body}>Compound lifting, progressive overload and sustainable strength cycles for beginner to advanced lifters.</Text></Card><View style={s.grid3}><Stat v="2.5K" l="Clients"/><Stat v="8 yrs" l="Experience"/><Stat v="4.9" l="Rating"/></View><Btn>Book Session</Btn></ScrollView>}

function Notifications(){return <ScrollView contentContainerStyle={s.pad}><H title="Notifications"/>{notifications.map(n=><Card key={n[0]}><Text style={s.h3}>{n[0]}</Text><Text style={s.body}>{n[1]}</Text><Text style={s.muted}>{n[2]}</Text></Card>)}</ScrollView>}
function Achievements(){return <ScrollView contentContainerStyle={s.pad}><H title="Achievements"/><Card><Text style={s.medal}>🏅</Text><Text style={s.h2}>10 Workouts Completed</Text><Text style={s.cyan}>Unlocked</Text></Card>{[["First Workout","100"],["7 Day Streak","100"],["20 Workouts","50"],["Nutrition Tracker","100"]].map(x=><Card key={x[0]}><View style={s.space}><Text style={s.h3}>{x[0]}</Text><Text style={s.cyan}>{x[1]}%</Text></View><ProgressBar value={+x[1]}/></Card>)}</ScrollView>}

function Schedule(){return <ScrollView contentContainerStyle={s.pad}><H title="Workout Schedule"/><View style={s.calendar}>{Array.from({length:28},(_,i)=><View key={i} style={[s.day,[1,2,4,5].includes(i+1)&&s.dayDone,i===5&&s.dayToday]}><Text style={s.small}>{i+1}</Text></View>)}</View><Card><Text style={s.h2}>This Week</Text>{[["Mon","Push Day","Done"],["Tue","Pull Day","Done"],["Thu","Leg Day","Upcoming"],["Sat","Full Body","Upcoming"]].map(x=><View key={x[0]} style={s.listRow}><Text style={s.body}>{x[0]} • {x[1]}</Text><Text style={x[2]==="Done"?s.cyan:s.muted}>{x[2]}</Text></View>)}</Card></ScrollView>}
function Goals(){return <ScrollView contentContainerStyle={s.pad}><H title="Goals"/>{[["Reach 70 kg",72],["Bench 100 kg",60],["12-week consistency",80]].map(x=><Card key={x[0]}><View style={s.space}><Text style={s.h2}>{x[0]}</Text><Text style={s.cyan}>{x[1]}%</Text></View><ProgressBar value={x[1]}/></Card>)}</ScrollView>}
function WeeklyReport(){return <ScrollView contentContainerStyle={s.pad}><H title="Weekly Report" sub="Your strongest week this month"/><View style={s.grid2}><Stat v="7" l="Workouts"/><Stat v="2,340" l="kcal burned"/><Stat v="12 days" l="Streak"/><Stat v="+11%" l="Bench trend"/></View><Card><Text style={s.h2}>AI Summary</Text><Text style={s.body}>Training consistency improved. Keep protein near 170g, schedule one recovery day, and increase bench press load by 2.5 kg next week.</Text></Card></ScrollView>}

function Profile({go}){return <ScrollView contentContainerStyle={s.pad}><Image source={hero} style={s.cover}/><H title="Edward James" sub="Premium Member"/><View style={s.grid3}><Stat v="48" l="Workouts"/><Stat v="12" l="Plans"/><Stat v="72.5" l="kg"/></View>{[["Edit Profile","EditProfile"],["Recovery & Sleep","Recovery"],["Hydration","Hydration"],["Body Measurements","BodyMeasurements"],["Nutrition Insights","NutritionInsights"],["My Plan","Plans"],["Exercise Library","ExerciseLibrary"],["Workout History","WorkoutHistory"],["Personal Records","PersonalRecords"],["Leaderboard","Leaderboard"],["Meal Planner","MealPlanner"],["Achievements","Achievements"],["Messages","Messages"],["Schedule","Schedule"],["Weekly Report","WeeklyReport"],["Connected Apps","ConnectedApps"],["Help & Support","Help"],["Settings","Settings"]].map(x=><TouchableOpacity key={x[0]} onPress={()=>go(x[1])}><Card><View style={s.space}><Text style={s.body}>{x[0]}</Text><Text>›</Text></View></Card></TouchableOpacity>)}<TouchableOpacity onPress={()=>go("Premium")}><Card style={s.premium}><Text style={s.kickerDark}>PREMIUM PLAN</Text><Text style={[s.h2,{color:"#03111d"}]}>$9.99 / month</Text><Text style={{color:"#18334c"}}>Next billing: 12 Jun 2026</Text></Card></TouchableOpacity></ScrollView>}
function Settings({state,setState}){return <ScrollView contentContainerStyle={s.pad}><H title="Settings"/>{["Account","Privacy","Appearance","Units","Language","Connected Apps"].map(x=><Card key={x}><View style={s.space}><Text style={s.body}>{x}</Text><Text>›</Text></View></Card>)}<Card><View style={s.space}><Text style={s.body}>Notifications</Text><Switch value={state.notificationsOn} onValueChange={v=>setState(s=>({...s,notificationsOn:v}))}/></View></Card><Card><View style={s.space}><Text style={s.body}>Workout Reminders</Text><Switch value={state.remindersOn} onValueChange={v=>setState(s=>({...s,remindersOn:v}))}/></View></Card></ScrollView>}
function Premium({go}){return <ScrollView contentContainerStyle={s.pad}><H title="Premium Plan" sub="Unlock your full AI fitness stack"/>{[["Basic","Free"],["Premium","$9.99 / month"],["Elite","$19.99 / month"]].map(x=><Card key={x[0]} style={x[0]==="Premium"&&{borderColor:T.cyan}}><Text style={s.kicker}>{x[0].toUpperCase()}</Text><Text style={s.big}>{x[1]}</Text><Text style={s.body}>✓ Workout tracking{"\n"}✓ AI guidance{"\n"}✓ Nutrition insights{"\n"}✓ Progress analytics</Text><Btn onPress={()=>x[0]==="Premium"&&go("Success")}>Choose {x[0]}</Btn></Card>)}</ScrollView>}

function Messages(){const [draft,setDraft]=useState("");const [msgs,setMsgs]=useState([{from:"Alex Carter",text:"Your next strength block is ready."},{from:"Emma Wilson",text:"Nutrition check-in tomorrow."}]);return <View style={s.screen}><ScrollView contentContainerStyle={s.pad}><H title="Messages" sub="Coaches & AIGYM support"/>{msgs.map((m,i)=><Card key={i}><Text style={s.h3}>{m.from}</Text><Text style={s.body}>{m.text}</Text></Card>)}</ScrollView><View style={s.composer}><TextInput value={draft} onChangeText={setDraft} placeholder="Write a message..." placeholderTextColor={T.muted} style={[s.input,{flex:1}]}/><TouchableOpacity style={s.send} onPress={()=>{if(draft.trim()){setMsgs(v=>[...v,{from:"You",text:draft.trim()}]);setDraft("")}}}><Text>➤</Text></TouchableOpacity></View></View>}
function Search({go}){const [q,setQ]=useState("");const items=[["Push Day","Workouts"],["Bench Press","Exercise"],["Muscle Gain Pro","Plans"],["Alex Carter","TrainerProfile"],["Nutrition","Nutrition"],["30 Day Fitness Challenge","Challenges"],["Weekly Report","WeeklyReport"],["Goals","Goals"]];const hits=items.filter(x=>x[0].toLowerCase().includes(q.toLowerCase()));return <ScrollView contentContainerStyle={s.pad}><H title="Search"/><TextInput value={q} onChangeText={setQ} placeholder="Search workouts, plans, trainers..." placeholderTextColor={T.muted} style={s.input}/>{hits.map(x=><TouchableOpacity key={x[0]} onPress={()=>go(x[1])}><Card><View style={s.space}><Text style={s.body}>{x[0]}</Text><Text>›</Text></View></Card></TouchableOpacity>)}</ScrollView>}
function Help(){return <ScrollView contentContainerStyle={s.pad}><H title="Help & Support"/>{[["Getting Started","Learn the dashboard, plans and tracking flow."],["Workout Help","Form, rest timers and exercise guidance."],["Billing","Premium plan and subscription questions."],["Privacy","Account, notifications and connected apps."]].map(x=><Card key={x[0]}><Text style={s.h2}>{x[0]}</Text><Text style={s.muted}>{x[1]}</Text></Card>)}</ScrollView>}
function ConnectedApps(){const [health,setHealth]=useState(true),[watch,setWatch]=useState(false),[scale,setScale]=useState(false);return <ScrollView contentContainerStyle={s.pad}><H title="Connected Apps"/>{[["Health Data",health,setHealth],["Smart Watch",watch,setWatch],["Smart Scale",scale,setScale]].map(x=><Card key={x[0]}><View style={s.space}><Text style={s.body}>{x[0]}</Text><Switch value={x[1]} onValueChange={x[2]}/></View></Card>)}</ScrollView>}
function EditProfile(){const [name,setName]=useState("Edward James"),[goal,setGoal]=useState("Build Muscle");return <ScrollView contentContainerStyle={s.pad}><H title="Edit Profile"/><TextInput value={name} onChangeText={setName} placeholderTextColor={T.muted} style={s.input}/><TextInput value={goal} onChangeText={setGoal} placeholderTextColor={T.muted} style={s.input}/><Card><Text style={s.muted}>Current weight</Text><Text style={s.h2}>72.5 kg</Text></Card><Btn>Save Profile</Btn></ScrollView>}


function WorkoutTimer(){const [seconds,setSeconds]=useState(60);const [running,setRunning]=useState(false);useEffect(()=>{if(!running||seconds<=0)return;const id=setInterval(()=>setSeconds(v=>v-1),1000);return()=>clearInterval(id)},[running,seconds]);return <View style={[s.pad,{flex:1,justifyContent:"center"}]}><Text style={s.kicker}>REST TIMER</Text><Text style={[s.big,{fontSize:72,textAlign:"center"}]}>{seconds}s</Text><Text style={[s.muted,{textAlign:"center"}]}>Bench Press • Set 2 of 4</Text><View style={s.row}><Btn onPress={()=>setRunning(v=>!v)}>{running?"Pause":"Start"}</Btn><Btn ghost onPress={()=>{setRunning(false);setSeconds(60)}}>Reset</Btn><Btn ghost onPress={()=>setSeconds(v=>v+15)}>+15s</Btn></View></View>}
function ExerciseLibrary({go}){const [q,setQ]=useState("");const items=[["Bench Press","Chest","4 × 12"],["Incline Dumbbell Press","Chest","4 × 12"],["Shoulder Press","Shoulders","4 × 10"],["Lat Pulldown","Back","4 × 12"],["Squat","Legs","4 × 10"],["Romanian Deadlift","Legs","4 × 10"],["Bicep Curl","Arms","4 × 12"],["Plank","Core","3 × 60s"]].filter(x=>x[0].toLowerCase().includes(q.toLowerCase()));return <ScrollView contentContainerStyle={s.pad}><H title="Exercise Library" sub="Search movements by name"/><TextInput value={q} onChangeText={setQ} placeholder="Search exercises..." placeholderTextColor={T.muted} style={s.input}/>{items.map(x=><TouchableOpacity key={x[0]} onPress={()=>go("Exercise")}><Card><View style={s.space}><View><Text style={s.h3}>{x[0]}</Text><Text style={s.muted}>{x[1]}</Text></View><Text style={s.cyan}>{x[2]}</Text></View></Card></TouchableOpacity>)}</ScrollView>}
function Leaderboard(){return <ScrollView contentContainerStyle={s.pad}><H title="Leaderboard" sub="Community rankings"/>{[["1","Alex Carter","2,450 pts"],["2","Sarah Khan","2,320 pts"],["3","Ryan Miller","2,150 pts"],["4","Emma Wilson","2,030 pts"],["5","Edward James","1,980 pts"]].map(x=><Card key={x[1]}><View style={s.space}><Text style={s.h3}>{x[0]} · {x[1]}</Text><Text style={s.cyan}>{x[2]}</Text></View></Card>)}</ScrollView>}
function MealPlanner(){return <ScrollView contentContainerStyle={s.pad}><H title="Meal Planner" sub="AI-generated daily plan"/>{[["Breakfast","Oatmeal, berries, Greek yogurt","420 kcal"],["Lunch","Chicken rice bowl + salad","610 kcal"],["Dinner","Salmon, potatoes, vegetables","680 kcal"],["Snack","Protein shake + banana","290 kcal"]].map(x=><Card key={x[0]}><Text style={s.h3}>{x[0]}</Text><Text style={s.muted}>{x[1]}</Text><Text style={s.cyan}>{x[2]}</Text></Card>)}<Card><Text style={s.h2}>Daily total</Text><Text style={s.big}>2,000</Text><Text style={s.muted}>of 2,300 kcal target</Text></Card><Btn>Regenerate with AI</Btn></ScrollView>}
function WorkoutHistory(){return <ScrollView contentContainerStyle={s.pad}><H title="Workout History" sub="Recent completed sessions"/>{[["Today","Push Day","50 min","320 kcal"],["Mon","Pull Day","48 min","295 kcal"],["Sat","Leg Day","55 min","410 kcal"],["Thu","Full Body","44 min","280 kcal"]].map(x=><Card key={x[0]+x[1]}><View style={s.space}><View><Text style={s.h3}>{x[1]}</Text><Text style={s.muted}>{x[0]} • {x[2]}</Text></View><Text style={s.cyan}>{x[3]}</Text></View></Card>)}</ScrollView>}
function PersonalRecords(){return <ScrollView contentContainerStyle={s.pad}><H title="Personal Records" sub="Strength milestones"/>{[["Bench Press","90 kg","+5 kg"],["Squat","120 kg","+10 kg"],["Deadlift","145 kg","+7.5 kg"],["Shoulder Press","55 kg","+2.5 kg"]].map(x=><Card key={x[0]}><View style={s.space}><View><Text style={s.h3}>{x[0]}</Text><Text style={s.muted}>Current PR</Text></View><View><Text style={s.h2}>{x[1]}</Text><Text style={s.cyan}>{x[2]}</Text></View></View></Card>)}</ScrollView>}


function ForgotPassword({go}){const [email,setEmail]=useState("");return <ScrollView contentContainerStyle={s.pad}><H title="Reset Password" sub="Enter your email to receive reset instructions."/><TextInput value={email} onChangeText={setEmail} placeholder="Email Address" placeholderTextColor={T.muted} style={s.input}/><Btn onPress={()=>go("Login")}>Send Reset Link</Btn><TouchableOpacity onPress={()=>go("Login")}><Text style={s.center}>Back to Login</Text></TouchableOpacity></ScrollView>}
function ProfileSetup({go}){const [goal,setGoal]=useState("Build Muscle"),[level,setLevel]=useState("Intermediate");return <ScrollView contentContainerStyle={s.pad}><H title="Set Up Your Profile" sub="A few details help personalize your plan."/><Card><Text style={s.h3}>Primary Goal</Text>{["Build Muscle","Lose Weight","Improve Fitness"].map(x=><TouchableOpacity key={x} onPress={()=>setGoal(x)} style={s.option}><Text style={goal===x?s.cyan:s.body}>{x}</Text></TouchableOpacity>)}</Card><Card><Text style={s.h3}>Training Level</Text>{["Beginner","Intermediate","Advanced"].map(x=><TouchableOpacity key={x} onPress={()=>setLevel(x)} style={s.option}><Text style={level===x?s.cyan:s.body}>{x}</Text></TouchableOpacity>)}</Card><View style={s.grid2}><Stat v="72.5 kg" l="Weight"/><Stat v="178 cm" l="Height"/></View><Btn onPress={()=>go("Home")}>Create My Plan →</Btn></ScrollView>}
function Recovery(){return <ScrollView contentContainerStyle={s.pad}><H title="Recovery & Sleep" sub="Readiness for today"/><View style={s.grid3}><Stat v="7h 42m" l="Sleep" accent={T.cyan}/><Stat v="82%" l="Recovery" accent={T.good}/><Stat v="62 bpm" l="Resting HR"/></View><Card><Text style={s.h2}>7-Day Sleep</Text><View style={s.chart}>{[68,74,61,80,76,88,82].map((h,i)=><View key={i} style={[s.bar,{height:h}]}/>)}</View></Card><Card><Text style={s.h2}>AI Recovery Notes</Text><Text style={s.body}>Sleep consistency is good. You’re ready for Push Day. Aim for a 10:45 PM bedtime to protect tomorrow’s recovery score.</Text></Card></ScrollView>}
function Hydration({state,setState}){return <ScrollView contentContainerStyle={s.pad}><H title="Hydration" sub="Daily water target"/><Card><View style={s.ring}><Text style={s.ringText}>{state.water}/8</Text></View><ProgressBar value={state.water/8*100}/><Text style={s.center}>Target: 8 glasses / day</Text><Btn onPress={()=>setState(v=>({...v,water:Math.min(8,v.water+1)}))}>+ Add Water</Btn></Card>{[["08:00","2 glasses"],["11:00","1 glass"],["14:00","2 glasses"],["17:00","1 glass"],["20:00","2 glasses"]].map(x=><Card key={x[0]}><View style={s.space}><Text style={s.body}>{x[0]}</Text><Text style={s.cyan}>{x[1]}</Text></View></Card>)}</ScrollView>}
function BodyMeasurements(){return <ScrollView contentContainerStyle={s.pad}><H title="Body Measurements" sub="Track body-composition trends"/><View style={s.grid3}><Stat v="72.5 kg" l="Weight"/><Stat v="14.5%" l="Body Fat"/><Stat v="54.2 kg" l="Muscle"/></View>{[["Chest","101 cm"],["Waist","82 cm"],["Arms","37 cm"],["Thighs","58 cm"],["Shoulders","118 cm"]].map(x=><Card key={x[0]}><View style={s.space}><Text style={s.body}>{x[0]}</Text><Text style={s.cyan}>{x[1]}</Text></View></Card>)}<Btn>Log New Measurements</Btn></ScrollView>}
function NutritionInsights(){return <ScrollView contentContainerStyle={s.pad}><H title="Nutrition Insights" sub="Weekly pattern analysis"/><Card><Text style={s.h2}>Protein Consistency</Text><ProgressBar value={71}/><Text style={s.muted}>Average: 142g / 170g target</Text></Card><Card><Text style={s.h2}>Calorie Adherence</Text><ProgressBar value={86}/><Text style={s.muted}>6 of 7 days within target range</Text></Card><Card><Text style={s.h2}>AI Insight</Text><Text style={s.body}>Add one 25–30g protein snack on training days to close the gap without pushing calories too high.</Text></Card></ScrollView>}

function Success({go}){return <View style={[s.pad,{flex:1,justifyContent:"center"}]}><Text style={s.medal}>✓</Text><Text style={[s.h1,{textAlign:"center"}]}>You’re All Set!</Text><Text style={[s.cyan,{textAlign:"center"}]}>Welcome to Premium</Text><Btn onPress={()=>go("Home")}>Start Exploring</Btn></View>}

const screens={Splash,Onboarding,SignUp:p=><Auth {...p}/>,Login:p=><Auth {...p} login/>,ForgotPassword,ProfileSetup,Home,Workouts,WorkoutDetail,Exercise,WorkoutTimer,ExerciseLibrary,Coach,Nutrition,NutritionInsights,MealPlanner,Recovery,Hydration,BodyMeasurements,Progress,PersonalRecords,WorkoutHistory,Plans,Challenges,Community,Leaderboard,Trainers,TrainerProfile,Notifications,Achievements,Schedule,Goals,WeeklyReport,Messages,Search,Help,ConnectedApps,EditProfile,Profile,Settings,Premium,Success};
export default function App(){const [screen,setScreen]=useState("Splash");const [state,setState]=useState({calories:234,foodCalories:1450,water:5,workoutDone:false,exerciseIndex:0,activePlan:"Muscle Gain Pro",notificationsOn:true,remindersOn:true});const [hydrated,setHydrated]=useState(false);useEffect(()=>{AsyncStorage.getItem("aigym-v10-state").then(v=>{if(v){try{setState(s=>({...s,...JSON.parse(v)}))}catch(e){}}}).finally(()=>setHydrated(true))},[]);useEffect(()=>{if(hydrated)AsyncStorage.setItem("aigym-v10-state",JSON.stringify(state))},[state,hydrated]);const C=screens[screen]||Home;const bottom=["Home","Workouts","Nutrition","Community","Profile"];return <SafeAreaView style={s.root}><View style={{flex:1}}><C go={setScreen} state={state} setState={setState}/></View>{bottom.includes(screen)&&<View style={s.nav}>{bottom.map(k=><TouchableOpacity key={k} onPress={()=>setScreen(k)}><Text style={[s.navT,screen===k&&s.navActive]}>{k}</Text></TouchableOpacity>)}</View>}</SafeAreaView>}

const s=StyleSheet.create({
 root:{flex:1,backgroundColor:T.bg},screen:{flex:1},full:{flex:1,backgroundColor:T.bg},bgimg:{...StyleSheet.absoluteFillObject,width:"100%",height:"100%",resizeMode:"cover"},overlay:{...StyleSheet.absoluteFillObject,backgroundColor:"rgba(2,7,18,.38)"},bottom:{position:"absolute",left:24,right:24,bottom:34,gap:14},
 logo:{fontSize:46,color:T.text,fontWeight:"900"},h1:{fontSize:31,color:T.text,fontWeight:"900",letterSpacing:-.5},h2:{fontSize:20,color:T.text,fontWeight:"850"},h3:{fontSize:16,color:T.text,fontWeight:"800"},big:{fontSize:42,color:T.text,fontWeight:"950"},statV:{fontSize:22,color:T.text,fontWeight:"900"},body:{fontSize:15,color:T.text,lineHeight:22},small:{fontSize:11,color:T.muted},sub:{fontSize:17,color:"#d8e5f4",lineHeight:24},muted:{color:T.muted},cyan:{color:T.cyan,fontWeight:"800"},check:{color:T.good,fontSize:18,fontWeight:"900"},center:{textAlign:"center",color:T.muted},kicker:{color:T.cyan,fontSize:10,fontWeight:"900",letterSpacing:1.2},kickerDark:{color:"#103047",fontSize:10,fontWeight:"900",letterSpacing:1.2},
 pad:{padding:18,paddingBottom:105,gap:12},card:{backgroundColor:T.panel,borderColor:T.line,borderWidth:1,borderRadius:18,padding:16,gap:8},stat:{flex:1,minWidth:96},btn:{backgroundColor:T.cyan,borderRadius:13,paddingVertical:14,paddingHorizontal:18,alignItems:"center",justifyContent:"center",minWidth:92},ghost:{backgroundColor:T.panel2,borderColor:T.line,borderWidth:1},btnT:{color:"#03121a",fontWeight:"900"},input:{backgroundColor:T.panel,borderColor:T.line,borderWidth:1,borderRadius:13,padding:14,color:T.text},
 row:{flexDirection:"row",gap:10,flexWrap:"wrap"},space:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",gap:12},grid2:{flexDirection:"row",flexWrap:"wrap",gap:10},grid3:{flexDirection:"row",gap:8},quick:{width:"22%",minWidth:72,backgroundColor:T.panel,borderColor:T.line,borderWidth:1,borderRadius:16,padding:12,alignItems:"center",gap:6},icon:{width:40,height:40,borderRadius:13,backgroundColor:T.panel2,alignItems:"center",justifyContent:"center"},iconText:{fontSize:20,color:T.cyan},tag:{color:T.text,backgroundColor:T.panel2,borderColor:T.line,borderWidth:1,paddingHorizontal:10,paddingVertical:6,borderRadius:99,fontSize:11},tagActive:{backgroundColor:T.cyan,color:"#03121a"},track:{height:8,backgroundColor:"#142b46",borderRadius:99,overflow:"hidden"},fill:{height:"100%",backgroundColor:T.cyan,borderRadius:99},
 ring:{width:78,height:78,borderRadius:39,borderWidth:9,borderColor:T.cyan,alignItems:"center",justifyContent:"center"},ringText:{color:T.text,fontWeight:"900"},cover:{width:"100%",height:220,borderRadius:20,resizeMode:"cover"},banner:{width:"100%",height:150,borderRadius:20,resizeMode:"cover"},bubble:{alignSelf:"flex-start",maxWidth:"86%",backgroundColor:T.panel2,borderRadius:16,padding:13,borderColor:T.line,borderWidth:1},mine:{alignSelf:"flex-end",backgroundColor:"#123d52"},option:{backgroundColor:T.panel2,borderColor:T.line,borderWidth:1,borderRadius:13,padding:13},composer:{flexDirection:"row",gap:8,padding:12,borderTopColor:T.line,borderTopWidth:1,backgroundColor:T.bg},send:{width:48,borderRadius:14,backgroundColor:T.cyan,alignItems:"center",justifyContent:"center"},
 chart:{height:150,flexDirection:"row",alignItems:"flex-end",gap:10,marginTop:10},bar:{flex:1,backgroundColor:T.cyan,borderRadius:8},avatar:{width:54,height:54,borderRadius:27,backgroundColor:T.panel2,borderColor:T.cyan,borderWidth:2,alignItems:"center",justifyContent:"center"},avatarT:{color:T.cyan,fontWeight:"900"},medal:{fontSize:70,textAlign:"center"},calendar:{flexDirection:"row",flexWrap:"wrap",gap:6},day:{width:"12.8%",aspectRatio:1,borderRadius:9,backgroundColor:T.panel,borderColor:T.line,borderWidth:1,alignItems:"center",justifyContent:"center"},dayDone:{backgroundColor:"#0c4e57"},dayToday:{borderColor:T.cyan,borderWidth:2},listRow:{flexDirection:"row",justifyContent:"space-between",paddingVertical:11,borderBottomColor:T.line,borderBottomWidth:1},premium:{backgroundColor:T.cyan,borderColor:T.purple},nav:{flexDirection:"row",justifyContent:"space-around",paddingVertical:13,backgroundColor:"#061428",borderTopColor:T.line,borderTopWidth:1},navT:{color:T.muted,fontSize:11},navActive:{color:T.cyan,fontWeight:"900"}
});